### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by verygreenboi** [ice-services/moleculer-examples#12]
I just tried the demo on glitch and it's broken. It seems like some of the services are unreachable.

![screenshot 2019-01-26 at 4 29 33 pm](https://user-images.githubusercontent.com/907685/51789285-a7bd1880-2187-11e9-9758-30a9c0d6b2ef.png)

**Comment by timjuravich** [comment]
Running the conduit service showed this error: ERROR: Service 'api' failed to build: The command '/bin/sh -c npm install --silent --progress=false --production' returned a non-zero code: 6

Looking onto the npm install errors, node-pre-gyp was failing due to an older version of bcrypt. Updating the version of bcrypt unblocked the error and is now running properly.
